### PR TITLE
Python bindings: Event callback support in Hostmod

### PR DESCRIPTION
**Pull request by imphil**
Support callbacks for received events in Hostmod.

@koenenwmn: Can you give this branch a try and see if it fits your needs?

You should be able to do something like that:

```python
def process_event(Packet pkg):
    print(pkg)
    return True

hostmod = Hostmod(log, 'tcp://...', process_event)
```

I don't have a full test setup ready at the moment so I didn't test the code beyond checking if it compiles. Can you give it a try and let me know how it goes?

### CODE REVIEW

**Comment by imphil** [comment]
Please test with `cd src/python; pytest tests/test_hostmod.py` if the callback works for you, and let me know if the tests don't pass on your end.

**Comment by koenenwmn** [comment]
The test you wrote works. I re-wrote it a bit to resemble my use case.  
The following works for me:
```
def test_event_hostmod_to_hostmod_callback(log, hostctrl):
    """Receive packet with callback"""
    class rcvmod(osd.Hostmod):
        def __init__(self, log, host_controller_address, event_handler=None, name=""):
            self.name = name
    class rcv_gw():
        def __init__(self, log, host_controller, handler, name=""):
            self.hm = rcvmod(log, host_controller, handler, name=name)
            self.hm.connect()
            assert self.hm.is_connected()
    rcvd = []
    def handler(pkt):
        rcvd.append(pkt)
        return True

    hm = osd.Hostmod(log, HOSTCTRL_ADDR)
    hm.connect()
    assert hm.is_connected()

    gw = rcv_gw(log, HOSTCTRL_ADDR, handler, name="gateway")
    assert gw.hm.name == "gateway"

    pkt_sent = []
    for i in range(10):
        pkt_sent.append(osd.Packet())
        pkt_sent[-1].set_header(dest=gw.hm.diaddr, src=hm.diaddr,
                                type=osd.Packet.TYPE_EVENT, type_sub=0)
        pkt_sent[-1].payload.append(i)
        hm.event_send(pkt_sent[-1])

    time.sleep(0.5)
    assert(len(rcvd) == len(pkt_sent))

    for i in range(10):
        assert pkt_sent[i].payload[0] == rcvd[i].payload[0]

    hm.disconnect()
    gw.hm.disconnect()
```
whereas this doesn't and ends in a Segmentation fault:
```
def test_event_hostmod_to_hostmod_callback(log, hostctrl):
    """Receive packet with callback"""
    class rcvmod(osd.Hostmod):
        def __init__(self, log, host_controller_address, event_handler=None, name=""):
            self.name = name
    class rcv_gw():
        def __init__(self, log, host_controller, name=""):
            self.hm = rcvmod(log, host_controller, self.handler, name=name)
            self.rcvd = []
            self.hm.connect()
            assert self.hm.is_connected()
        def handler(pkt):
            self.rcvd.append(pkt.payload)
            return True

    hm = osd.Hostmod(log, HOSTCTRL_ADDR)
    hm.connect()
    assert hm.is_connected()

    gw = rcv_gw(log, HOSTCTRL_ADDR, name="gateway")
    assert gw.hm.name == "gateway"

    pkt_sent = []
    for i in range(10):
        pkt_sent.append(osd.Packet())
        pkt_sent[-1].set_header(dest=gw.hm.diaddr, src=hm.diaddr,
                                type=osd.Packet.TYPE_EVENT, type_sub=0)
        pkt_sent[-1].payload.append(i)
        hm.event_send(pkt_sent[-1])

    time.sleep(0.5)
    assert(len(gw.rcvd) == len(pkt_sent))

    for i in range(10):
        assert pkt_sent[i].payload[0] == gw.rcvd[i].payload[0]

    hm.disconnect()
    gw.hm.disconnect()
```

**Comment by imphil** [comment]
@koenenwmn can you give it another try? The Python callback function wasn't in scope any more when it got called (it was already garbage collected). That should be fixed now, together with a range of other small bugs. 

The GIL problem you experienced could also be gone, but I'm not overly confident that it actually is gone. The code looks good in general, so we need to dig deeper if the current version doesn't solve it for you.

**Comment by koenenwmn** [comment]
You are right, in both cases. The test works now for me, but when I try the same in my script I still get the GIL problem.

**Comment by imphil** [comment]
OK. So this is merged now as it clearly improves things. For the GIL issue, please file an issue with with more information or anything that could help me reproduce the bug. I currently don't have sufficient information to even guess what might be going on.

**Pull request merged**
